### ISSUE TITLE
Add additional docs/tests/comments on use of UID/GID

### ISSUE THREAD

**Issue by lumjjb** [IBM/k8s-enc-image-operator#20]
Add some comments so that golang consumers understand the implications of the config. i.e. for `KeyServerConfig`, indicate that `-1` is disable - OR even better would be ensuring that the default value of the fields of `KeyServerConfig` should be default. i.e. using an *int instead of int since 0 is reserved for an actual useful value. This prevents misuse of someone configuring `KeyServerConfig` without the field ending up in requiring CAP_CHOWN and making everything owned by root.

https://github.com/IBM/k8s-enc-image-operator/commit/0e043d998eba049496c7a50c3dcf08c73a2d3293#diff-b77636c946f63caa24ab7aad7911eb98fecd999aebd0519f661dca9b71a23799R83

We should also add some unit tests for this functionality.

**Comment by lumjjb** [comment]
@attiss when you have some time after delivery date line, could you take a look at this - mostly QOL.

**Comment by attiss** [comment]
sure, will take care of this
could you assign me to this issue?
